version: '3.7'

networks:
  bulk-message-network:
    driver: bridge

services:
  bulk-message-postgres:
    image: postgres
    container_name: database_bulk_message_sql
    ports:
      - 5454:5454
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bulk_message
    volumes:
      - pgdata:/data/postgres
    command: -p 5454
    networks:
      - bulk-message-network

  bulk-message-mongo:
    image: mongo
    container_name: bulk-message-mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - "15017:27017"
    volumes:
      - bulk-message-mongo-data:/data/db
    networks:
      - bulk-message-network

  bulk-message-redis:
    image: bitnami/redis:latest
    container_name: bulk-message-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - bulk-message-redis-data:/bitnami/redis/data
    networks:
      - bulk-message-network


volumes:
  bulk-message-redis-data:
  bulk-message-mongo-data:
  pgdata:
    driver: local
