version: '3'

networks:
  umbriel-network:
    driver: bridge

services: 
  umbriel-api:
    build: .
    container_name: umbriel-api
    command: yarn dev
    volumes:
      - .:/home/node/api
    ports:
      - 3333:3333
    environment: 
      - MONGO_URL=mongo
      - REDIS_URL=redis
    depends_on: 
      - umbriel-mongo
      - umbriel-redis
    networks:
      - umbriel-network

  umbriel-mongo:
    image: mongo:4
    container_name: umbriel-mongo
    restart: always
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
    volumes:
      - umbriel-mongo-data:/data/db
    networks:
      - umbriel-network

  umbriel-redis:
    image: bitnami/redis:latest
    container_name: umbriel-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - umbriel-redis-data:/bitnami/redis/data
    networks:
      - umbriel-network

volumes:
  umbriel-redis-data:
  umbriel-mongo-data: